server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cafedb
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true