server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cafedb
    username: postgres
    password: newpassword123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect